{
 "title": "HPC Viz",
 "time": { "from": "2021-08-11T05:00:00.000Z", "to": "2021-08-11T08:00:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "Nocona",
    "query": "select nodeid as __value, hostname as __text from nodes where nodeid > 488"
   },
   {
    "name": "UsersNocona",
    "query": "SELECT\n user_id as __value, user_name as __text\nFROM\n  slurm.jobs\nWHERE\npartition = 'nocona'\nAND start_time < ${__to:date:seconds} AND end_time > ${__from:date:seconds}"
   },
   {
    "name": "NodeByUser",
    "query": "SELECT DISTINCT unnest(nodes)as node FROM slurm.jobs WHERE user_id IN ($UsersNocona) AND partition = 'nocona' AND start_time < ${__to:date:seconds} AND end_time > ${__from:date:seconds}"
   },
   {
    "name": "Quanah",
    "query": "select nodeid as __value, hostname as __text from nodes where nodeid <=467"
   }
  ]
 },
 "panels": [
  { "title": "Nocona", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nocona - Parallel coordinate",
   "type": "idvl-hpcc-parallel-coordinate",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  avg(value) AS \"memory_power\",\n  CONCAT('| ',nodes.hostname) AS name\nFROM idrac9.totalmemorypower\nINNER JOIN nodes\nON nodes.nodeid = idrac9.totalmemorypower.nodeid\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  idrac9.totalmemorypower.nodeid IN ($Nocona)\nGROUP BY time,name\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  avg(value) AS \"power_consumption\",\n  CONCAT('| ',nodes.hostname) AS name\nFROM idrac9.systempowerconsumption\nINNER JOIN nodes\nON nodes.nodeid = idrac9.systempowerconsumption.nodeid\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  idrac9.systempowerconsumption.nodeid IN ($Nocona)\nGROUP BY time,name\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  avg(value) AS \"CPU1_Temp\",\n  CONCAT('| ',nodes.hostname) AS name\nFROM idrac9.temperaturereading\nINNER JOIN nodes\nON nodes.nodeid = idrac9.temperaturereading.nodeid\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  idrac9.temperaturereading.nodeid IN ($Nocona) AND\n  fqdd = 'iDRAC.Embedded.1#CPU1Temp'\nGROUP BY time,name\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  avg(value) AS \"CPU2_Temp\",\n  CONCAT('| ',nodes.hostname) AS name\nFROM idrac9.temperaturereading\nINNER JOIN nodes\nON nodes.nodeid = idrac9.temperaturereading.nodeid\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  idrac9.temperaturereading.nodeid IN ($Nocona) AND\n  fqdd = 'iDRAC.Embedded.1#CPU2Temp'\nGROUP BY time,name\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  avg(value) AS \"NIC_Temp\",\n  CONCAT('| ',nodes.hostname) AS name\nFROM idrac9.temperaturereading\nINNER JOIN nodes\nON nodes.nodeid = idrac9.temperaturereading.nodeid\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  idrac9.temperaturereading.nodeid IN ($Nocona) AND\n  fqdd = 'NIC.Embedded.1-1-1'\nGROUP BY time,name\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  avg(value) AS \"Fan 1\",\n  CONCAT('| ',nodes.hostname) AS name\nFROM idrac9.rpmreading\nINNER JOIN nodes\nON nodes.nodeid = idrac9.rpmreading.nodeid\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  idrac9.rpmreading.nodeid IN ($Nocona) AND\n  fqdd = 'Fan.Embedded.1A'\nGROUP BY time,name\nORDER BY time"
    }
   ]
  },
  {
   "title": "Spiral Layout",
   "type": "hpcviz-idvl-hpcc-spiral-layout",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 1 },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "Sankey",
   "type": "hpcviz-idvl-hpcc-sankey",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    { "panelId": 9 }
   ]
  },
  {
   "title": "Query by User",
   "type": "hpcviz-idvl-hpcc-stream-net",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroupAlias(a.timestamp,$__interval), a.name, a.jobs, a.cpus from ( \r\n                SELECT  timestamp, CONCAT(nodes.hostname) AS name, jobs, cpus, nodes.hostname AS source_ip\r\n                FROM slurm.node_jobs a \r\n                INNER JOIN nodes\r\n                ON nodes.nodeid = a.nodeid\r\n                WHERE $__timeFilter(a.timestamp)\r\n) AS a WHERE a.source_ip IN ($NodeByUser) GROUP BY a.timestamp, a.name, a.jobs, a.cpus ORDER BY a.timestamp"
    },
    {
     "rawSql": "SELECT\n  *\nFROM\n  slurm.jobs\nWHERE\n  user_id IN ($UsersNocona)\n  AND partition = 'nocona'\n  AND start_time < ${__to:date:seconds}\n  AND end_time > ${__from:date:seconds}"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  avg(value) AS \"CPU_usage\",\n  CONCAT('| ',nodes.hostname) AS name\nFROM idrac9.cpuusage\nINNER JOIN nodes\nON nodes.nodeid = idrac9.cpuusage.nodeid\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  nodes.hostname IN ($NodeByUser)\nGROUP BY time,name\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  avg(value) AS \"CPU1_Temp\",\n  CONCAT('| ',nodes.hostname) AS name\nFROM idrac9.temperaturereading\nINNER JOIN nodes\nON nodes.nodeid = idrac9.temperaturereading.nodeid\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  nodes.hostname IN ($NodeByUser) AND\n  fqdd = 'iDRAC.Embedded.1#CPU1Temp'\nGROUP BY time,name\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  avg(value) AS \"CPU2_Temp\",\n  CONCAT('| ',nodes.hostname) AS name\nFROM idrac9.temperaturereading\nINNER JOIN nodes\nON nodes.nodeid = idrac9.temperaturereading.nodeid\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  nodes.hostname IN ($NodeByUser) AND\n  fqdd = 'iDRAC.Embedded.1#CPU2Temp'\nGROUP BY time,name\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  avg(value) AS \"Memory_usage\",\n  CONCAT('| ',nodes.hostname) AS name\nFROM slurm.memoryusage\nINNER JOIN nodes\nON nodes.nodeid = slurm.memoryusage.nodeid\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  nodes.hostname IN ($NodeByUser)\nGROUP BY time,name\nORDER BY time"
    }
   ]
  },
  {
   "title": "Quanah",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Quanah - Parallel coordinate",
     "type": "hpcviz-idvl-hpcc-parallel-coordinate",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  avg(value) AS \"memory_power\",\n  CONCAT('| ',nodes.hostname) AS name\nFROM idrac9.totalmemorypower\nINNER JOIN nodes\nON nodes.nodeid = idrac9.totalmemorypower.nodeid\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  idrac9.totalmemorypower.nodeid IN ($Quanah)\nGROUP BY time,name\nORDER BY time"
      },
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  avg(value) AS \"power_consumption\",\n  CONCAT('| ',nodes.hostname) AS name\nFROM idrac9.systempowerconsumption\nINNER JOIN nodes\nON nodes.nodeid = idrac9.systempowerconsumption.nodeid\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  idrac9.systempowerconsumption.nodeid IN ($Quanah)\nGROUP BY time,name\nORDER BY time"
      },
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  avg(value) AS \"CPU1_Temp\",\n  CONCAT('| ',nodes.hostname) AS name\nFROM idrac9.temperaturereading\nINNER JOIN nodes\nON nodes.nodeid = idrac9.temperaturereading.nodeid\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  idrac9.temperaturereading.nodeid IN ($Quanah) AND\n  fqdd = 'iDRAC.Embedded.1#CPU1Temp'\nGROUP BY time,name\nORDER BY time"
      },
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  avg(value) AS \"CPU2_Temp\",\n  CONCAT('| ',nodes.hostname) AS name\nFROM idrac9.temperaturereading\nINNER JOIN nodes\nON nodes.nodeid = idrac9.temperaturereading.nodeid\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  idrac9.temperaturereading.nodeid IN ($Quanah) AND\n  fqdd = 'iDRAC.Embedded.1#CPU2Temp'\nGROUP BY time,name\nORDER BY time"
      },
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  avg(value) AS \"NIC_Temp\",\n  CONCAT('| ',nodes.hostname) AS name\nFROM idrac9.temperaturereading\nINNER JOIN nodes\nON nodes.nodeid = idrac9.temperaturereading.nodeid\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  idrac9.temperaturereading.nodeid IN ($Quanah) AND\n  fqdd = 'NIC.Embedded.1-1-1'\nGROUP BY time,name\nORDER BY time"
      },
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  avg(value) AS \"Fan 1\",\n  CONCAT('| ',nodes.hostname) AS name\nFROM idrac9.rpmreading\nINNER JOIN nodes\nON nodes.nodeid = idrac9.rpmreading.nodeid\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  idrac9.rpmreading.nodeid IN ($Quanah) AND\n  fqdd = 'Fan.Embedded.1A'\nGROUP BY time,name\nORDER BY time"
      }
     ]
    }
   ]
  },
  {
   "title": "Quanah - Parallel coordinate",
   "type": "hpcviz-idvl-hpcc-parallel-coordinate",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  avg(value) AS \"power_consumption\",\n  CONCAT('| ',nodes.hostname) AS name\nFROM idrac8.systempowerconsumption\nINNER JOIN nodes\nON nodes.nodeid = idrac8.systempowerconsumption.nodeid\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  idrac8.systempowerconsumption.nodeid IN ($Quanah)\nGROUP BY time,name\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  avg(value) AS \"CPU1_Temp\",\n  CONCAT('| ',nodes.hostname) AS name\nFROM idrac8.temperaturereading\nINNER JOIN nodes\nON nodes.nodeid = idrac8.temperaturereading.nodeid\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  idrac8.temperaturereading.nodeid IN ($Quanah) AND\n  fqdd = 'CPU1 Temp'\nGROUP BY time,name\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  avg(value) AS \"CPU2_Temp\",\n  CONCAT('| ',nodes.hostname) AS name\nFROM idrac8.temperaturereading\nINNER JOIN nodes\nON nodes.nodeid = idrac8.temperaturereading.nodeid\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  idrac8.temperaturereading.nodeid IN ($Quanah) AND\n  fqdd = 'CPU2 Temp'\nGROUP BY time,name\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  avg(value) AS \"Inlet_Temp\",\n  CONCAT('| ',nodes.hostname) AS name\nFROM idrac8.temperaturereading\nINNER JOIN nodes\nON nodes.nodeid = idrac8.temperaturereading.nodeid\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  idrac8.temperaturereading.nodeid IN ($Quanah) AND\n  fqdd = 'Inlet Temp'\nGROUP BY time,name\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  avg(value) AS \"Fan 1\",\n  CONCAT('| ',nodes.hostname) AS name\nFROM idrac8.rpmreading\nINNER JOIN nodes\nON nodes.nodeid = idrac8.rpmreading.nodeid\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  idrac8.rpmreading.nodeid IN ($Quanah) AND\n  fqdd = 'Fan.Embedded.1A'\nGROUP BY time,name\nORDER BY time"
    }
   ]
  },
  {
   "title": "Power Map",
   "type": "hpcviz-idvl-hpcc-stream-net",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "rawSql": "SELECT\n  *\nFROM\n  slurm.jobs\nWHERE\n  user_id IN ($Users)\n  AND start_time < ${__to:date:seconds}\n  AND end_time BETWEEN ${__from:date:seconds} and ${__to:date:seconds}\n"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  avg(value) AS \"memory_power\",\n  CONCAT('| ',nodes.hostname) AS name\nFROM idrac9.totalmemorypower\nINNER JOIN nodes\nON nodes.nodeid = idrac9.totalmemorypower.nodeid\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  idrac9.totalmemorypower.nodeid IN ($Nocona)\nGROUP BY time,name\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  avg(value) AS \"cpu_power\",\n  CONCAT('| ',nodes.hostname) AS name\nFROM idrac9.totalcpupower\nINNER JOIN nodes\nON nodes.nodeid = idrac9.totalcpupower.nodeid\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  idrac9.totalcpupower.nodeid IN ($Nocona)\nGROUP BY time,name\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  avg(value) AS \"CPU1_Temp\",\n  CONCAT('| ',nodes.hostname) AS name\nFROM idrac9.temperaturereading\nINNER JOIN nodes\nON nodes.nodeid = idrac9.temperaturereading.nodeid\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  idrac9.temperaturereading.nodeid IN ($Nocona) AND\n  fqdd = 'iDRAC.Embedded.1#CPU1Temp'\nGROUP BY time,name\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  avg(value) AS \"CPU2_Temp\",\n  CONCAT('| ',nodes.hostname) AS name\nFROM idrac9.temperaturereading\nINNER JOIN nodes\nON nodes.nodeid = idrac9.temperaturereading.nodeid\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  idrac9.temperaturereading.nodeid IN ($Nocona) AND\n  fqdd = 'iDRAC.Embedded.1#CPU2Temp'\nGROUP BY time,name\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  avg(value) AS \"NIC_Temp\",\n  CONCAT('| ',nodes.hostname) AS name\nFROM idrac9.temperaturereading\nINNER JOIN nodes\nON nodes.nodeid = idrac9.temperaturereading.nodeid\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  idrac9.temperaturereading.nodeid IN ($Nocona) AND\n  fqdd = 'NIC.Embedded.1-1-1'\nGROUP BY time,name\nORDER BY time"
    }
   ]
  }
 ]
}